### PR TITLE
modify dict implementation, fix typo

### LINKED ISSUE #64: Setting environment variables on remote cluster does not work
* RHG Compute Tools version: 0.2.1
* Python version: 3.7.3
* Operating System: Linux-4.14.138+-x86_64-with-debian-buster-sid

### Description

I'm trying to set an environment variable on a remote cluster. It appears that the dictionary implementation assigning values to names is slightly off (`values()` should be `items()`). Also, the handling for the deprecated list-of-dicts implementation has a typo (`isintance` should be `isinstance`) (I am submitting a PR to resolve both issues).

### What I Did

```
client, cluster = rhg_compute_tools.kubernetes.get_standard_cluster(
    env_items = {
        'FOO':'/path/to/bar'
    }
)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-18c512dee399> in <module>
      1 client, cluster = rhg_compute_tools.kubernetes.get_standard_cluster(
      2     env_items = {
----> 3         'FOO':'/path/to/bar'
      4     }
      5 )

~/rhg_compute_tools/rhg_compute_tools/kubernetes.py in get_standard_cluster(*args, **kwargs)
    316     """
    317 
--> 318     return get_cluster(*args, scaling_factor=1, **kwargs)
    319 
    320 

~/rhg_compute_tools/rhg_compute_tools/kubernetes.py in get_cluster(name, extra_pip_packages, extra_conda_packages, memory_gb, nthreads, cpus, cred_name, cred_path, env_items, scaling_factor, dask_config_dict, deploy_mode, idle_timeout, template_path, extra_worker_labels, extra_pod_tolerations, keep_default_tolerations, **kwargs)
    221             [
    222                 container["env"].append({"name": k, "value": v})
--> 223                 for k, v in env_items.values()
    224             ]
    225         # allow deprecated passing of list of name/value pairs

~/rhg_compute_tools/rhg_compute_tools/kubernetes.py in <listcomp>(.0)
    221             [
    222                 container["env"].append({"name": k, "value": v})
--> 223                 for k, v in env_items.values()
    224             ]
    225         # allow deprecated passing of list of name/value pairs

ValueError: too many values to unpack (expected 2)
```

### PR DESCRIPTION
**Pull request by dpa9694**
- [x] closes #64 
 - [x] tests added / passed
 - [x] docs reflect changes
 - [ ] passes ``flake8 rhg_compute_tools tests docs``
 - [ ] entry in HISTORY.rst

This updates the handling of the `env_items` parameter in `get_cluster()`, changing the dictionary unpacking to `for k, v in env_items.items()` instead of `for k, v in env_items.values()`.

Also, this fixes a typo in the deprecated list-of-dicts implementation (from `isintance` to `isinstance`).

Finally, the docstring is updated to match the dict implementation rather than the deprecated list-of-dicts implementation.

### CODE REVIEW

**Comment by delgadom** [comment]
The CI failures look like they're likely an issue with a new version of pytest. I've triggered a build on master to see if we get the same issue.

**Comment by delgadom** [comment]
Have a fix in #67. We can merge this in once that is merged into master

**Comment by delgadom** [comment]
Note this PR is waiting on https://github.com/dpa9694/rhg_compute_tools/pull/2

**Comment by dpa9694** [comment]
@delgadom I merged in those changes, looks like this is passing tests (which seem to have sped up 5-10x??)

**Pull request merged**
